services:
  - type: web
    name: guruai-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    rootDirectory: server
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: RESEND_API_KEY
        sync: false
      - key: FROM_EMAIL
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: GEMINI_API_KEY_2
        sync: false
      - key: GEMINI_API_KEY_3
        sync: false
      - key: GEMINI_API_KEY_4
        sync: false
